roster_data = [
    {"number":"1", "name":"Marissa", "image":"roster_photos/marissa.png", "score": 0},
    {"number":"2", "name":"Jeylin", "image":"roster_photos/jeylin.png", "score": 0},
    {"number":"3", "name":"Stephanie", "image":"roster_photos/stephanie.png", "score": 0},
    {"number":"5", "name":"Lana", "image":"roster_photos/lana.png", "score": 0},
    {"number":"6", "name":"Rena", "image":None, "score": 0},
    {"number":"8", "name":"Alize", "image":"roster_photos/alize.png", "score": 0},
    {"number":"9", "name":"Brittany", "image":"roster_photos/brittany.png", "score": 0},
    {"number":"10", "name":"Shreeya", "image":"roster_photos/shreeya.png", "score": 0},
    {"number":"11", "name":"Emma", "image":None, "score": 0},
    {"number":"12", "name":"Ailsa", "image":"roster_photos/ailsa.png", "score": 0},
    {"number":"14", "name":"Veda", "image":None, "score": 0},
    {"number":"16", "name":"Giulia", "image":"roster_photos/giulia.png", "score": 0},
    {"number":"17", "name":"Andrea", "image":"roster_photos/andrea.png", "score": 0},
    {"number":"22", "name":"Noelle", "image":"roster_photos/noelle.png", "score": 0},
]